### ISSUE TITLE
Discord Testers is closing

### ISSUE THREAD

**Issue by nmsturcke** [Discord-Resources-Wiki/Discord-Resources-Wiki#243]
Specify in the wiki that Discord Testers is closing (in `official-servers.md`) or remove it from the list of official servers.

**Comment by rydixulous** [comment]
we will be removing discord tester's invite as soon as possible from all current languages of the wiki.
we are trying to define the best way to to add / remove resources from the wiki, as the process is getting a lot bigger as we support new languages.

**Comment by DyDestroyer1027** [comment]
maccroe has trolled us all

**Comment by DyDestroyer1027** [comment]
discord testers is not in fact closing forever, it will be kept around with all locked channels and used to communicate about future opportunities 
![image](https://user-images.githubusercontent.com/42097667/184042531-61057089-bab0-4549-af9f-e0556a14f12e.png)

**Comment by nmsturcke** [comment]
> discord testers is not in fact closing forever, it will be kept around with all locked channels and used to communicate about future opportunities
> ![image](https://user-images.githubusercontent.com/42097667/184042531-61057089-bab0-4549-af9f-e0556a14f12e.png)

oh they changed their minds again

**Comment by nmsturcke** [comment]
I'll mark this as resolved then

**Comment by Meqativ** [comment]
just remove it while it's archived
