### ISSUE TITLE
Inconsistency with full stops in descriptions

### ISSUE THREAD

**Issue by nmsturcke** [Discord-Resources-Wiki/Discord-Resources-Wiki#267]
Some pages descriptions have full stops, and others don't.

For example, `programs.md`:
```MD
description: Discord programs like Moderation, Partner, HSE and Verification.
```

Whereas `moderation.md`:
```MD
description: Moderation resources
```

I think you should decide whether if they should have full stops or not and make it consistent throughout all files (and translations!)

**Comment by JantsoP** [comment]
As no one has done nothing about this, I will close this issue.
Feel free to make adjustments yourself and then make a pull request :)
