### ISSUE TITLE
Domain Changed

### ISSUE THREAD

**Issue by nmsturcke** [Discord-Resources-Wiki/Discord-Resources-Wiki#277]
The link in the wiki for the [Nadeko Embed Previewer](https://discordresources.com/resources/unofficial-resources/#nadeko-embed-builder) in [unofficial-resources.md](https://github.com/Discord-Resources-Wiki/Discord-Resources-Wiki/blob/main/wiki/resources/unofficial-resources.md) is no longer valid.

The new domain for the bot is https://nadeko.bot but I can't find the embed builder subdomain

**Comment by GeneralSadaf** [comment]
> The link in the wiki for the [Nadeko Embed Previewer](https://discordresources.com/resources/unofficial-resources/#nadeko-embed-builder) in [unofficial-resources.md](https://github.com/Discord-Resources-Wiki/Discord-Resources-Wiki/blob/main/wiki/resources/unofficial-resources.md) is no longer valid.
> 
> The new domain for the bot is https://nadeko.bot but I can't find the embed builder subdomain

Should be here https://eb.nadeko.bot/

**Comment by JantsoP** [comment]
Closed with #283
