### ISSUE TITLE
Bug: User tags display with a dark background in lightmode

### ISSUE THREAD

**Issue by nmsturcke** [Discord-Resources-Wiki/Discord-Resources-Wiki#278]
## Summary
User tags are displayed as if dark mode was enabled, when in reality everything else is light and the selected mode is light mode.

## Reproduction steps
1. Go to any page in the Wiki, e.g https://discordresources.com/contribution
2. Select light mode
3. Add a forward-slash (`/`) at the end of the URL
4. Notice the background of the user tags turn dark, but the page remains light

## Expected results
The url without a forward-slash (`/`) at the end and the one with display user tags with a light background.

## Actual results
In the url with a forward-slash (`/`) at the end, the tag displays in dark mode, even when the page is set to light mode.

## Media
`https://discordresources.com/contribution` 

![image](https://user-images.githubusercontent.com/30734036/185693149-4dc84cdc-2690-4fed-8d6e-0bbcd3ee0cb1.png)

`https://discordresources.com/contribution/`

![image](https://user-images.githubusercontent.com/30734036/185693205-7da69fef-178c-4afb-8d93-2c0644332993.png)

**Comment by JantsoP** [comment]
Bug in Docusaurus. Not on site. Closing issue.
