### ISSUE TITLE
Discord Creator Center is now retired

### ISSUE THREAD

**Issue by kesku** [Discord-Resources-Wiki/Discord-Resources-Wiki#434]
![image](https://github.com/Discord-Resources-Wiki/Discord-Resources-Wiki/assets/62210496/8bb3c7de-c05b-4aad-864c-594ec18f004d)

On https://discordresources.com/resources/official-servers/ the server is still classed as "Currently under construction."

**Comment by JantsoP** [comment]
Will be updated in soon to come merge
