### ISSUE TITLE
Useful links under Fun Links

### ISSUE THREAD

**Issue by Smeagol2069** [Discord-Resources-Wiki/Discord-Resources-Wiki#82]
I feel there are some links like lightmode.glitch.me and truesize that are more for functional than fun purposes. Should they go somewhere else? I feel like they are worthwhile, but maybe not the best spot as most links under fun are memes.

**Comment by rydixulous** [comment]
they can go somewhere else, maybe under "Discord Related" in Tools"

**Comment by Smeagol2069** [comment]
I think this can be closed now, if there are any other resources that should be moved elsewhere feel free to reopen.
